services:
  github-runner:
    image: myoung34/github-runner:latest
    container_name: github-runner
    environment:
      - REPO_URL=${REPO_URL}
      - RUNNER_TOKEN=${RUNNER_TOKEN}  
      - RUNNER_NAME='my-runner'
      - RUNNER_WORKDIR='/tmp/runner'
      - LABELS='docker,self-hosted'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - github-runner:/runner/data
      - github-runner-tmp:/tmp/runner

volumes:
  github-runner:
    name: github-runner
  github-runner-tmp:
    name: github-runner-tmp

