services:
  nginx:
    image: nginx:alpine-slim
    container_name: nginx
    ports:
      - '443:443'
    volumes:
      - nginx_data:/etc/nginx/conf.d
      - serts:/etc/letsencrypt

volumes:
  nginx_data:
    name: nginx_data
  serts:
    name: serts


