services:
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep -v grep | grep gitlab-runner || exit 1"]
      interval: 30s
      timeout: 2s
      retries: 1
      start_period: 10s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-config:/etc/gitlab-runner

volumes:
  runner-config:
    name: runner-config
