name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted   # или runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - name: Проверка
        run: |
          echo "Привет"
          uname -a
